<a href="https://colab.research.google.com/github/AbhiSinghDeveloper/Machine-Learning/blob/master/Basics_of_%20Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install numpy

In [0]:
pwd

'/content'

In [0]:
import numpy as np

In [0]:
#The basics :- 1d Array

a = np.array([1,2,3],dtype = 'int8')
print(a)

[1 2 3]


In [0]:
#The basics :- 2d Array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [0]:
#To know the dimension

b.ndim

2

In [0]:
#To know the shape

b.shape

(2, 3)

In [0]:
print(a.dtype)

int8


In [0]:
a.size

3

In [0]:
a.itemsize

1

In [0]:
a.size * a.itemsize

24

In [0]:
a.nbytes

24

In [0]:
#Accessing the data elements

a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]], dtype = 'float32')
print(a)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]]


In [0]:
a.ndim

2

In [0]:
a.shape

(2, 8)

In [0]:
random_var = a

In [0]:
type(random_var)

numpy.ndarray

In [0]:
a.dtype

dtype('float32')

In [0]:
a[0,0]

1.0

In [0]:
print(a[0,:])

[1. 2. 3. 4. 5. 6. 7. 8.]


In [0]:
print(a[:,0])

[1. 9.]


In [0]:
a[:,:]

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.]], dtype=float32)

In [0]:
a[0,1:6:2]

array([2., 4., 6.], dtype=float32)

In [0]:
a[0,0] = 100

In [0]:
a

array([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.]], dtype=float32)

In [0]:
a[0,:] = 2

In [0]:
a

array([[ 2,  2,  2,  2,  2,  2,  2,  2],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [0]:
a[:,6] = 1000

In [0]:
a

array([[   2.,    2.,    2.,    2.,    2.,    2., 1000.,    2.],
       [   9.,   10.,   11.,   12.,   13.,   14., 1000.,   16.]],
      dtype=float32)

In [0]:
a.nbytes

64

In [0]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [0]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [0]:
c.ndim

3

In [0]:
c.nbytes

96

In [0]:
print(c[0,:,:])

[[1 2 3]
 [4 5 6]]


In [0]:
c[0,:,:] = np.array([[200,300,400],[500,600,700]])

In [0]:
c

array([[[200, 300, 400],
        [500, 600, 700]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [0]:
d = np.ones((2,2),dtype = 'int8')

In [0]:
d

array([[1, 1],
       [1, 1]], dtype=int8)

In [0]:
d.dtype

dtype('int8')

In [0]:
e = np.zeros((2,2),dtype = 'int8')

In [0]:
e

array([[0, 0],
       [0, 0]], dtype=int8)

In [0]:
f = np.full((2,2), 100, dtype = 'int32')

In [0]:
f

array([[100, 100],
       [100, 100]], dtype=int32)

In [0]:
print(np.full_like(a))


In [0]:
f = np.ones([5,5])
f[1:4,1:4]=[[0,0,0],[0,9,0],[0,0,0]]
f

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
g = np.ones((5,5))
g[1:4,1:4]=0
g[2,2]=9
g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
#Advanced concepts

#1 :- Linear Algebra


arr = np.array([[1,2,3],[4,5,6]])

In [0]:
arr.shape

(2, 3)

In [0]:
new_arr = arr.reshape(3,2)

In [0]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
new_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
product = np.matmul(arr,new_arr)

array([[22, 28],
       [49, 64]])

In [0]:
h = np.identity(3)
print(h)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
np.linalg.det(h)

1.0

In [0]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [0]:
print(np.vstack([v1,v2,v1,v2,v2,v1]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [1 2 3]]


In [0]:
print(np.hstack([v1,v2,v1,v2,v2,v1]))

[1 2 3 4 5 6 1 2 3 4 5 6 4 5 6 1 2 3]


In [0]:
pwd

'/content'

In [0]:
ls

abc.txt  sample_data/


In [0]:
#Read a file using Numpy

filedata = np.genfromtxt('abc.txt', delimiter = ',', dtype = 'int8')

In [0]:
filedata

array(-1, dtype=int8)

Pandas

In [0]:
pip install pandas


In [0]:
import pandas as pd
import matplotlib.pyplot as plt


In [0]:
df = pd.read_csv('pokemon_data.csv')

In [0]:
df

#                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
4      4             Charmander     Fire  ...    65           1      False
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion     Fire  ...    70           6       True

[800 rows x 12 columns]

In [0]:
print(df.head(3))

   #       Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
0  1  Bulbasaur  Grass  Poison  ...       65     45           1      False
1  2    Ivysaur  Grass  Poison  ...       80     60           1      False
2  3   Venusaur  Grass  Poison  ...      100     80           1      False

[3 rows x 12 columns]


In [0]:
df = pd.read_csv('pokemon_data.txt', delimiter = '\t')

In [0]:
df

#                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
4      4             Charmander     Fire  ...    65           1      False
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion     Fire  ...    70           6       True

[800 rows x 12 columns]

In [0]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [0]:
print(df.Name)

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object


In [0]:
print(df['Name'])

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object


In [0]:
print(df['Name'], ['Type '])

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object ['Type ']


In [0]:
print(df['Name'][0:5])

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object


In [0]:
print(df[['Name','HP'][0:5]])

                      Name  HP
0                Bulbasaur  45
1                  Ivysaur  60
2                 Venusaur  80
3    VenusaurMega Venusaur  80
4               Charmander  39
..                     ...  ..
795                Diancie  50
796    DiancieMega Diancie  50
797    HoopaHoopa Confined  80
798     HoopaHoopa Unbound  80
799              Volcanion  80

[800 rows x 2 columns]


In [0]:
df.iloc[1]

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [0]:
df.iloc[1:3]

#      Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
1  2   Ivysaur  Grass  Poison  ...       80     60           1      False
2  3  Venusaur  Grass  Poison  ...      100     80           1      False

[2 rows x 12 columns]

In [0]:
for index, row in df.iterrows():
  print(index,row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 

In [0]:
df.loc[df['Type 1'] == 'Fire']

#                       Name Type 1  ... Speed  Generation  Legendary
4      4                 Charmander   Fire  ...    65           1      False
5      5                 Charmeleon   Fire  ...    80           1      False
6      6                  Charizard   Fire  ...   100           1      False
7      6  CharizardMega Charizard X   Fire  ...   100           1      False
8      6  CharizardMega Charizard Y   Fire  ...   100           1      False
42    37                     Vulpix   Fire  ...    65           1      False
43    38                  Ninetales   Fire  ...   100           1      False
63    58                  Growlithe   Fire  ...    60           1      False
64    59                   Arcanine   Fire  ...    95           1      False
83    77                     Ponyta   Fire  ...    90           1      False
84    78                   Rapidash   Fire  ...   105           1      False
135  126                     Magmar   Fire  ...    93           1      False
147  136                    Flareon   Fire  ...    65           1      False
158  146                    Moltres   Fire  ...    90           1       True
169  155                  Cyndaquil   Fire  ...    65           2      False
170  156                    Quilava   Fire  ...    80           2      False
171  157                 Typhlosion   Fire  ...   100           2      False
236  218                     Slugma   Fire  ...    20           2      False
237  219                   Magcargo   Fire  ...    30           2      False
259  240                      Magby   Fire  ...    83           2      False
263  244                      Entei   Fire  ...   100           2       True
270  250                      Ho-oh   Fire  ...    90           2       True
276  255                    Torchic   Fire  ...    45           3      False
277  256                  Combusken   Fire  ...    55           3      False
278  257                   Blaziken   Fire  ...    80           3      False
279  257      BlazikenMega Blaziken   Fire  ...   100           3      False
352  322                      Numel   Fire  ...    35           3      False
353  323                   Camerupt   Fire  ...    40           3      False
354  323      CameruptMega Camerupt   Fire  ...    20           3      False
355  324                    Torkoal   Fire  ...    20           3      False
435  390                   Chimchar   Fire  ...    61           4      False
436  391                   Monferno   Fire  ...    81           4      False
437  392                  Infernape   Fire  ...   108           4      False
518  467                  Magmortar   Fire  ...    83           4      False
542  485                    Heatran   Fire  ...    77           4       True
557  498                      Tepig   Fire  ...    45           5      False
558  499                    Pignite   Fire  ...    55           5      False
559  500                     Emboar   Fire  ...    65           5      False
572  513                    Pansear   Fire  ...    64           5      False
573  514                   Simisear   Fire  ...   101           5      False
614  554                   Darumaka   Fire  ...    50           5      False
615  555    DarmanitanStandard Mode   Fire  ...    95           5      False
616  555         DarmanitanZen Mode   Fire  ...    55           5      False
692  631                    Heatmor   Fire  ...    65           5      False
721  653                   Fennekin   Fire  ...    60           6      False
722  654                    Braixen   Fire  ...    73           6      False
723  655                    Delphox   Fire  ...   104           6      False
730  662                Fletchinder   Fire  ...    84           6      False
731  663                 Talonflame   Fire  ...   126           6      False
735  667                     Litleo   Fire  ...    72           6      False
736  668                     Pyroar   Fire  ...   106           6      False
799

In [0]:
df.loc[df['Legendary'] == True]

#                 Name    Type 1  ... Speed  Generation  Legendary
156  144             Articuno       Ice  ...    85           1       True
157  145               Zapdos  Electric  ...   100           1       True
158  146              Moltres      Fire  ...    90           1       True
162  150               Mewtwo   Psychic  ...   130           1       True
163  150  MewtwoMega Mewtwo X   Psychic  ...   130           1       True
..   ...                  ...       ...  ...   ...         ...        ...
795  719              Diancie      Rock  ...    50           6       True
796  719  DiancieMega Diancie      Rock  ...   110           6       True
797  720  HoopaHoopa Confined   Psychic  ...    70           6       True
798  720   HoopaHoopa Unbound   Psychic  ...    80           6       True
799  721            Volcanion      Fire  ...    70           6       True

[65 rows x 12 columns]

In [0]:
df.describe()

#          HP      Attack  ...     Sp. Def       Speed  Generation
count  800.000000  800.000000  800.000000  ...  800.000000  800.000000   800.00000
mean   362.813750   69.258750   79.001250  ...   71.902500   68.277500     3.32375
std    208.343798   25.534669   32.457366  ...   27.828916   29.060474     1.66129
min      1.000000    1.000000    5.000000  ...   20.000000    5.000000     1.00000
25%    184.750000   50.000000   55.000000  ...   50.000000   45.000000     2.00000
50%    364.500000   65.000000   75.000000  ...   70.000000   65.000000     3.00000
75%    539.250000   80.000000  100.000000  ...   90.000000   90.000000     5.00000
max    721.000000  255.000000  190.000000  ...  230.000000  180.000000     6.00000

[8 rows x 8 columns]

In [0]:
df.sort_values(['Type 1'], ascending = True)

#      Name Type 1    Type 2  ...  Sp. Def  Speed  Generation  Legendary
600  540  Sewaddle    Bug     Grass  ...       60     42           5      False
136  127    Pinsir    Bug       NaN  ...       70     85           1      False
457  412     Burmy    Bug       NaN  ...       45     36           4      False
132  123   Scyther    Bug    Flying  ...       80    105           1      False
656  595    Joltik    Bug  Electric  ...       50     65           5      False
..   ...       ...    ...       ...  ...      ...    ...         ...        ...
172  158  Totodile  Water       NaN  ...       48     43           2      False
610  550  Basculin  Water       NaN  ...       55     98           5      False
145  134  Vaporeon  Water       NaN  ...       95     65           1      False
574  515   Panpour  Water       NaN  ...       48     64           5      False
184  170  Chinchou  Water  Electric  ...       56     67           2      False

[800 rows x 12 columns]

In [0]:
df.sort_values(['Type 1', 'HP'], ascending = [0,1])

#                     Name Type 1  ... Speed  Generation  Legendary
139  129                 Magikarp  Water  ...    80           1      False
381  349                   Feebas  Water  ...    80           3      False
97    90                 Shellder  Water  ...    40           1      False
106   98                   Krabby  Water  ...    50           1      False
125  116                   Horsea  Water  ...    60           1      False
..   ...                      ...    ...  ...   ...         ...        ...
232  214  HeracrossMega Heracross    Bug  ...    75           2      False
678  617                 Accelgor    Bug  ...   145           5      False
734  666                 Vivillon    Bug  ...    89           6      False
698  637                Volcarona    Bug  ...   100           5      False
520  469                  Yanmega    Bug  ...    95           4      False

[800 rows x 12 columns]

In [0]:
df['Total'] = df['Attack'] + df['HP']

In [0]:
df

#                   Name   Type 1  ... Generation  Legendary  Total
0      1              Bulbasaur    Grass  ...          1      False     94
1      2                Ivysaur    Grass  ...          1      False    122
2      3               Venusaur    Grass  ...          1      False    162
3      3  VenusaurMega Venusaur    Grass  ...          1      False    180
4      4             Charmander     Fire  ...          1      False     91
..   ...                    ...      ...  ...        ...        ...    ...
795  719                Diancie     Rock  ...          6       True    150
796  719    DiancieMega Diancie     Rock  ...          6       True    210
797  720    HoopaHoopa Confined  Psychic  ...          6       True    190
798  720     HoopaHoopa Unbound  Psychic  ...          6       True    240
799  721              Volcanion     Fire  ...          6       True    190

[800 rows x 13 columns]

In [0]:
df.drop(columns = ['Total'])

#                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
4      4             Charmander     Fire  ...    65           1      False
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion     Fire  ...    70           6       True

[800 rows x 12 columns]

In [0]:
df.head(20)

#                       Name Type 1  ... Generation  Legendary  Total
0    1                  Bulbasaur  Grass  ...          1      False     94
1    2                    Ivysaur  Grass  ...          1      False    122
2    3                   Venusaur  Grass  ...          1      False    162
3    3      VenusaurMega Venusaur  Grass  ...          1      False    180
4    4                 Charmander   Fire  ...          1      False     91
5    5                 Charmeleon   Fire  ...          1      False    122
6    6                  Charizard   Fire  ...          1      False    162
7    6  CharizardMega Charizard X   Fire  ...          1      False    208
8    6  CharizardMega Charizard Y   Fire  ...          1      False    182
9    7                   Squirtle  Water  ...          1      False     92
10   8                  Wartortle  Water  ...          1      False    122
11   9                  Blastoise  Water  ...          1      False    162
12   9    BlastoiseMega Blastoise  Water  ...          1      False    182
13  10                   Caterpie    Bug  ...          1      False     75
14  11                    Metapod    Bug  ...          1      False     70
15  12                 Butterfree    Bug  ...          1      False    105
16  13                     Weedle    Bug  ...          1      False     75
17  14                     Kakuna    Bug  ...          1      False     70
18  15                   Beedrill    Bug  ...          1      False    155
19  15      BeedrillMega Beedrill    Bug  ...          1      False    215

[20 rows x 13 columns]

In [0]:
df.to_csv('modified.csv', index = True)

In [0]:
ls

abc.txt        modified.csv      pokemon_data.txt
modified1.csv  pokemon_data.csv  sample_data/


In [0]:
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 70)]

In [0]:
new_df

#                   Name Type 1  ... Generation  Legendary  Total
0    3               Venusaur  Grass  ...          1      False    162
1    3  VenusaurMega Venusaur  Grass  ...          1      False    180
2   45              Vileplume  Grass  ...          1      False    155
3   71             Victreebel  Grass  ...          1      False    185
4  591              Amoonguss  Grass  ...          5      False    199

[5 rows x 13 columns]

In [0]:
new_df.reset_index(drop = True, inplace = True)

In [0]:
new_df.to_csv('modified1.csv', index = 'True')

In [0]:
ls

abc.txt        modified.csv      pokemon_data.txt
modified1.csv  pokemon_data.csv  sample_data/
